#!/bin/bash
wget -O ./webpage "$1"
./find_images < ./webpage > ./urls_unsorted
sort -u ./urls_unsorted > ./urls
rm -rf -- ./out ./webpage ./urls_unsorted
mkdir ./out
cd ./out
xargs -0 -n 1 wget < <(tr \\n \\0 <../urls)
cd ..
rm ./urls

